# Generated by Django 4.1.3 on 2024-02-07 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='Status',
            field=models.CharField(choices=[('PENDING', 'pending'), ('COMPLETE', 'complete'), ('CANCELED', 'canceled')], default='PENDING', max_length=10),
        ),
    ]
